CREATE TABLE "PACIENTE" (
"PACIENTEID" INT NOT NULL PRIMARY KEY
GENERATED ALWAYS AS IDENTITY
(START WITH 1, INCREMENT BY 1),
"CEDULA" VARCHAR(15),
"NOMBRE" VARCHAR(55),
"FECHANACIMIENTO" DATE,
"ESTATURA"  INT,
"PESO" INT
);

CREATE TABLE "TERAPIA" (
"TERAPIAID" INT NOT NULL PRIMARY KEY
GENERATED ALWAYS AS IDENTITY
(START WITH 1, INCREMENT BY 1),
"PACIENTEID" INT,
"FECHA" DATE,
"OBSERVACION" VARCHAR(255),
"RESPONSABLE" VARCHAR(10),
"REALIZADA" BOOLEAN
);

ALTER TABLE TERAPIA
ADD CONSTRAINT PACIENTE_FK
FOREIGN KEY (PACIENTEID)
REFERENCES PACIENTE(PACIENTEID);